trigger:
- none

pool:
  vmImage: 'windows-latest'

parameters:
- name: resourcegroup
  displayName: 'Resource Group Name'
  type: string
- name: environment
  displayName: 'Environment'
  type: string
  values:
  - 'Non-Prod'
  - 'Prod'
- name: tagsToFilter
  displayName: 'Tags to Filter'
  type: string
  default: 'owner,deploymentid'
- name: ContainerFolder
  default: "Inventory"

variables:
  - group: ${{ parameters.environment }}

jobs:
- job: RunPowerShellScript
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: 'latest'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - powershell: |
      # Instala PowerShell 7 desde PowerShellGet
      Install-Module -Name PowerShellGet -Force -AllowClobber -Scope CurrentUser
      Install-Package -Name powershell -Force -AllowClobber -Scope CurrentUser -Repository PSGallery

      # Verifica la versión instalada
      $PSVersionTable.PSVersion
    displayName: 'Install Latest PowerShell'

  - powershell: |
      # Ejecuta tu script PowerShell con argumentos
      .\Scripts\az_inventory.ps1 -ResourceGroup ${{ parameters.resourcegroup }} -TagsToFilter ${{ parameters.tagsToFilter }}
    displayName: 'Run PowerShell Script with Arguments'