trigger:
- none

pool:
  vmImage: 'windows-latest'

parameters:
- name: resourcegroup
  displayName: 'Resource Group Name'
  type: string
- name: environment
  displayName: 'Environment'
  type: string
  values:
  - 'Non-Prod'
  - 'Prod'
- name: tagsToFilter
  displayName: 'Tags to Filter'
  type: string
  default: 'owner,deploymentid'

variables:
  - group: ${{ parameters.environment }}

steps:
- template: Modules/azurepowershell.yaml

- task: AzureCLI@2
  displayName: 'Generating RG Inventory'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'pscore'
    scriptPath: '$(Build.SourcesDirectory)/Scripts/az_inventory.ps1'

- task: AzurePowerShell@5
  displayName: 'Upload Inventory to Azure Blob Storage'
  inputs:
    azureSubscription: $(azureSubscription)
    ScriptType: 'InlineScript'
    Inline: |
      $sourceFilePath = 'Resources_${{parameters.resourcegroup}}.csv'
      $destinationBlobName = 'Inventory/Resources_${{parameters.resourcegroup}}.csv'
      
      $storageContext = New-AzStorageContext -StorageAccountName $(storageAccountName) -StorageAccountKey $(storageAccountAccessKey)
      $blob = Set-AzStorageBlobContent -Context $storageContext -Container $(storageContainerName) -File $sourceFilePath -Blob $destinationBlobName -Force

    azurePowerShellVersion: LatestVersion
